{{- if .Values.indexer.api.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-nomad-indexer-api"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-nomad-indexer-api"
  minReplicas: {{ .Values.indexer.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.indexer.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.indexer.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.indexer.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.indexer.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.indexer.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}