apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nomad-indexer-api
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 3000
  selector:
    environment: {{ .Values.environment }}
    app.kubernetes.io/component: indexer-api
---
{{- if .Values.indexer.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nomad-indexer-api-ingress
  annotations:
    {{- if .Values.indexer.api.ingress.annotations }}
    {{- toYaml .Values.indexer.api.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-nomad-indexer-api
      port:
        number: 8000
{{- end }}