apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ .Release.Name }}-indexer-env
data:
  {{- range $rpc_key, $rpc_url := .Values.indexer.rpcs }}
  {{ $rpc_key | upper }}: {{ $rpc_url | quote }}
  {{- end }}
  ENVIRONMENT: {{ .Values.environment | quote }}

  PORT: {{ .Values.indexer.internalPort | quote }}
  BATCH_SIZE: {{ .Values.indexer.rpc_batch_size | quote }}
  PROGRAM: "core"
  DATABASE_URL: postgres://{{ .Values.indexer.db.user }}:{{ .Values.indexer.db.password }}@{{ tpl .Values.indexer.db.host . }}:{{ .Values.indexer.db.port }}/{{ .Values.indexer.db.database }}?connect_timeout=300&schema=public