apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  selector:
    environment: {{ .Values.serviceAgreementApi.environment }}
    app.kubernetes.io/component: service-agreement-api
---
{{- if .Values.serviceAgreementApi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}-ingress
  annotations:
    {{- if .Values.serviceAgreementApi.ingress.annotations }}
    {{- toYaml .Values.serviceAgreementApi.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ include "service.fullname" . }}-svc
      port:
        number: 8080
{{- end }}
