apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.serviceAgreementApi.databaseUrl }}
