apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxyd.fullname" . }}
  labels:
    {{- include "proxyd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxyd.selectorLabels" . | nindent 6 }}
      environment: {{ .Values.environment }}
      network: {{ .Values.network }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxyd.selectorLabels" . | nindent 8 }}
        environment: {{ .Values.environment }}
        network: {{ .Values.network }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxyd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.proxyd.server.rpc_port }}
              protocol: TCP
            # - name: wss
            #   containerPort: {{ .Values.proxyd.server.ws_port }}
            #   protocol: TCP
            - name: metrics
              containerPort: {{ .Values.proxyd.metrics.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8545
            initialDelaySeconds: 5
            periodSeconds:       10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8545
            initialDelaySeconds: 5
            periodSeconds:       10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: {{ .Values.proxyd.config.path }}
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
