apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxyd.fullname" . }}
  labels:
    {{- include "proxyd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8545
      protocol: TCP
      name: http
  selector:
    {{- include "proxyd.selectorLabels" . | nindent 4 }}
