imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

environment: development
indexer:
  image:
    repository: gcr.io/nomad-xyz/nomad-indexer
    pullPolicy: Always
    tag: "sha-2354e1d8"
  db:
    host: "{{ .Release.Name }}-postgresql"
    user: postgres
    password: postgres
    database: nomad-indexer
    port: 5432
  loglevel: info
  redis:
    url: redis://redis:6379
  overrideConfigUrl: ""
  rpcs:
    {}
    # ethereum_rpc: "https://main-light.eth.linkpool.io"
    # moonbeam_rpc: "https://rpc.api.moonbeam.network"
    # ....

postgresql:
  # ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L437-L441
  postgresql:
    username: postgres
    password: postgres
    database: nomad-indexer
    # ref: https://kubernetes.io/docs/user-guide/compute-resources/
    primary:
      resources:
        requests:
          cpu: 2000m

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"

podCommonLabels: {}

storage:
  storageClass: "standard"
  accessModes: ReadWriteOnce
  size: 10Gi
  snapshot:
    enabled: false
    name: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

core:
  rpcBatchSize: 3000
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    # limits:
    #   cpu:
    #   memory:
    requests:
      cpu: 500m
      memory: 900Mi

api:
  internalPort: 3000
  replicas: 1
  ingress:
    enabled: true
    annotations: {}
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    # limits:
    #   cpu:
    #   memory:
    requests:
      cpu: 200m
      memory: 700Mi

nodeSelector: {}

tolerations: []

affinity: {}
