{{- if .Values.updater.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "agent.fullname" . }}-updater
  labels: {{- include "agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: updater
spec:
  selector:
    matchLabels: {{- include "agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: updater
  replicas: {{ .Values.updater.replicas }}
  serviceName: {{ include "agent.fullname" . }}-updater-svc
  template:
    metadata:
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.updater.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "agent.labels" . | nindent 8 }}
        app.kubernetes.io/component: updater
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.updater.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: nomad-agent
          image: "{{ .Values.updater.image.registry }}/{{ .Values.updater.image.repository }}:{{ .Values.updater.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.updater.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command: ["./updater"]
          envFrom:
            - secretRef:
                name: {{ include "agent.fullname" . }}-awscreds
          {{- with .Values.commonEnvFrom }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.updater.envFrom }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.commonEnvVars }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.updater.envVars }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.updater.resources }}
          resources: {{- toYaml .Values.updater.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: state
              mountPath: {{ .Values.storage.mountPath }}
          ports: 
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
      {{- include "agent.serviceAccountName" . | nindent 6 }}
      {{- with .Values.updater.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: state
    spec:
      storageClassName: {{ .Values.storage.storageClass }}
      accessModes: [ {{ .Values.storage.accessModes }} ]
      resources:
        requests:
          storage: {{ .Values.storage.capacity }}
{{- end }}
