apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-awscreds
  namespace: {{ .Release.Namespace }}
  labels: {{- include "agent.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $aws_key, $aws_value := .Values.aws }}
  {{ $aws_key | upper }}: {{ $aws_value | b64enc | quote }}
  {{- end }}
