apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keymaster.fullname" . }}
  labels: {{- include "keymaster.labels" . | nindent 4 }}
    app.kubernetes.io/component: keymaster
spec:
  selector:
    matchLabels: {{- include "keymaster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keymaster
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.keymaster.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "keymaster.labels" . | nindent 8 }}
        app.kubernetes.io/component: keymaster
        {{- with .Values.keymaster.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: nomad-keymaster
          image: "{{ .Values.keymaster.image.registry }}/{{ .Values.keymaster.image.repository }}:{{ .Values.keymaster.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.keymaster.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.keymaster.envFrom }}
          envFrom:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.keymaster.envVars }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.keymaster.resources }}
          resources: {{- toYaml .Values.keymaster.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: keymaster-config
              mountPath: /config
              readOnly: true
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "keymaster.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.keymaster.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keymaster.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keymaster.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: keymaster-config
          configMap:
            name: {{ include "keymaster.fullname" . }}-config
