apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailscale.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "tailscale.fullname" . }}
  apiGroup: rbac.authorization.k8s.io