apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "tailscale.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  AUTH_KEY: {{ .Values.config.authKey }}